"""add checkin_date to CheckIn

Revision ID: 13aab5ab7663
Revises: 414e46ba6da6
Create Date: 2025-04-19 17:15:08.014902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13aab5ab7663'
down_revision: Union[str, None] = '414e46ba6da6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkins', sa.Column('checkin_date', sa.Date(), nullable=False))
    op.drop_constraint('uix_user_date', 'checkins', type_='unique')
    op.create_unique_constraint('uix_user_date', 'checkins', ['user_id', 'checkin_date'])
    op.drop_column('checkins', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkins', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint('uix_user_date', 'checkins', type_='unique')
    op.create_unique_constraint('uix_user_date', 'checkins', ['user_id', 'date'])
    op.drop_column('checkins', 'checkin_date')
    # ### end Alembic commands ###
