"""Centralize association tables

Revision ID: 7082a4d512d1
Revises: dd0e8d77ef8a
Create Date: 2025-04-18 14:43:31.911832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7082a4d512d1'
down_revision: Union[str, None] = 'dd0e8d77ef8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medication_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_medication_options_id'), 'medication_options', ['id'], unique=False)
    op.create_table('migraine_medications',
    sa.Column('migraine_id', sa.Integer(), nullable=False),
    sa.Column('medication_option_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['medication_option_id'], ['medication_options.id'], ),
    sa.ForeignKeyConstraint(['migraine_id'], ['migraines.id'], ),
    sa.PrimaryKeyConstraint('migraine_id', 'medication_option_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('migraine_medications')
    op.drop_index(op.f('ix_medication_options_id'), table_name='medication_options')
    op.drop_table('medication_options')
    # ### end Alembic commands ###
