"""Add user_id to migraines table

Revision ID: 76c38921ec81
Revises: 5de21caec1c4
Create Date: 2025-04-11 15:11:43.282302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76c38921ec81'
down_revision: Union[str, None] = '5de21caec1c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('migraines', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('migraines', sa.Column('weather', sa.JSON(), nullable=True))
    op.drop_constraint('migraines_userid_fkey', 'migraines', type_='foreignkey')
    op.create_foreign_key(None, 'migraines', 'users', ['user_id'], ['id'])
    op.drop_column('migraines', 'userid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('migraines', sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'migraines', type_='foreignkey')
    op.create_foreign_key('migraines_userid_fkey', 'migraines', 'users', ['userid'], ['id'])
    op.drop_column('migraines', 'weather')
    op.drop_column('migraines', 'user_id')
    # ### end Alembic commands ###
