"""Add start_time and end_time to migraines

Revision ID: 7785b2c18f4e
Revises: 12cbcb5d1f67
Create Date: 2025-04-15 11:18:58.352687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7785b2c18f4e'
down_revision: Union[str, None] = '12cbcb5d1f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add start_time with a TEMPORARY default (to satisfy NOT NULL constraint)
    op.add_column(
        'migraines',
        sa.Column(
            'start_time',
            sa.DateTime(),
            nullable=False,
            server_default=sa.text('NOW()')  # use current timestamp
        )
    )

    # Add end_time (can be null)
    op.add_column(
        'migraines',
        sa.Column(
            'end_time',
            sa.DateTime(),
            nullable=True
        )
    )

    # Drop the old timestamp column
    op.drop_column('migraines', 'timestamp')

    # Remove the default so future inserts must explicitly provide start_time
    op.alter_column('migraines', 'start_time', server_default=None)
    

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('migraines', sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('migraines', 'end_time')
    op.drop_column('migraines', 'start_time')
    # ### end Alembic commands ###
