"""Change pain_map to array of integers

Revision ID: bd9f7e6da7a8
Revises: 13aab5ab7663
Create Date: 2025-04-22 13:04:52.858951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd9f7e6da7a8'
down_revision: Union[str, None] = '13aab5ab7663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
