"""Add sleep tracking to CheckIn

Revision ID: dcebbf513ec1
Revises: 8dce6a188779
Create Date: 2025-05-15 17:17:48.521845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcebbf513ec1'
down_revision: Union[str, None] = '8dce6a188779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1: Add new columns as nullable (or with server default)
    op.add_column('checkins', sa.Column(
        'time_went_to_bed',
        sa.Time(),
        nullable=False,
        server_default='00:00:00'
    ))
    op.add_column('checkins', sa.Column(
        'time_woke_up',
        sa.Time(),
        nullable=False,
        server_default='00:00:00'
    ))
    op.add_column('checkins', sa.Column(
        'total_sleep_hours',
        sa.Float(),
        nullable=False,
        server_default='0'
    ))

    # Optional Step 2 (remove default if you want stricter future inserts)
    op.alter_column('checkins', 'time_went_to_bed', server_default=None)
    op.alter_column('checkins', 'time_woke_up', server_default=None)
    op.alter_column('checkins', 'total_sleep_hours', server_default=None)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checkins', 'total_sleep_hours')
    op.drop_column('checkins', 'time_woke_up')
    op.drop_column('checkins', 'time_went_to_bed')
    # ### end Alembic commands ###
