"""Add many-to-many symptoms and triggers

Revision ID: dd0e8d77ef8a
Revises: 7785b2c18f4e
Create Date: 2025-04-17 16:55:03.863658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd0e8d77ef8a'
down_revision: Union[str, None] = '7785b2c18f4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symptom_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_symptom_options_id'), 'symptom_options', ['id'], unique=False)
    op.create_table('trigger_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_trigger_options_id'), 'trigger_options', ['id'], unique=False)
    op.create_table('migraine_symptoms',
    sa.Column('migraine_id', sa.Integer(), nullable=False),
    sa.Column('symptom_option_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['migraine_id'], ['migraines.id'], ),
    sa.ForeignKeyConstraint(['symptom_option_id'], ['symptom_options.id'], ),
    sa.PrimaryKeyConstraint('migraine_id', 'symptom_option_id')
    )
    op.create_table('migraine_triggers',
    sa.Column('migraine_id', sa.Integer(), nullable=False),
    sa.Column('trigger_option_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['migraine_id'], ['migraines.id'], ),
    sa.ForeignKeyConstraint(['trigger_option_id'], ['trigger_options.id'], ),
    sa.PrimaryKeyConstraint('migraine_id', 'trigger_option_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('migraine_triggers')
    op.drop_table('migraine_symptoms')
    op.drop_index(op.f('ix_trigger_options_id'), table_name='trigger_options')
    op.drop_table('trigger_options')
    op.drop_index(op.f('ix_symptom_options_id'), table_name='symptom_options')
    op.drop_table('symptom_options')
    # ### end Alembic commands ###
