"""Change pain_map to array of integers

Revision ID: f695b1926d9a
Revises: ddb4adda3ba2
Create Date: 2025-04-22 15:46:53.341865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f695b1926d9a'
down_revision: Union[str, None] = 'ddb4adda3ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE migraines ALTER COLUMN pain_map TYPE INTEGER[] USING ARRAY[pain_map]")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
